/**
 * Cross-model faithfulness gate for ContentEngine (`content-engine/1.0`).
 *
 * After a draft is generated by the primary LLM (claude-sonnet-4.5), this
 * gate runs a DIFFERENT model (claude-haiku-4-5) to independently verify that
 * every factual claim in the body traces to the provided source snippets.
 *
 * Independence is the key invariant: the verifier model must differ from
 * the draft model so we get a genuine second opinion, not a self-consistency
 * check from the same weights.
 *
 * Gate failure (LLM error, parse error, timeout) is always soft:
 *   → returns { skipped: true, skipReason: 'gate-error', verdict: 'PARTIAL', ... }
 *   → the draft is never blocked
 *
 * PII rule: never log draft body or claim text.
 */

import "server-only";

// ── Types ────────────────────────────────────────────────────────────────────

export type ClaimVerdict = "SOURCED" | "UNSOURCED" | "CONTRADICTED";

export interface ClaimResult {
  /** Exact claim text as it appears in the draft body */
  claim: string;
  verdict: ClaimVerdict;
  /** Which source URL supports it (populated for SOURCED claims; always a URL present in brief.sources) */
  sourceUrl?: string;
  /** Brief note explaining a contradiction (populated for CONTRADICTED claims) */
  notes?: string;
}

export interface FaithfulnessResult {
  /** 0-100 percentage of claims that are SOURCED */
  sourcedPercent: number;
  totalClaims: number;
  sourcedCount: number;
  unsourcedCount: number;
  contradictedCount: number;
  claims: ClaimResult[];
  /**
   * FAITHFUL:   ≥80% sourced AND 0 contradicted
   * PARTIAL:    50-79% sourced OR (<80% but 0 contradicted)
   * UNFAITHFUL: <50% sourced OR any CONTRADICTED
   */
  verdict: "FAITHFUL" | "PARTIAL" | "UNFAITHFUL";
  /**
   * true when no sources were available (sources[].length === 0)
   * or when the LLM call itself failed (gate failure = soft)
   */
  skipped: boolean;
  /**
   * Distinguishes WHY the gate was skipped:
   *   'no-sources'  — brief had no web sources to verify against
   *   'gate-error'  — LLM gate call failed (network, parse, timeout, etc.)
   * Only present when skipped === true.
   */
  skipReason?: "no-sources" | "gate-error";
}

// ── Constants ─────────────────────────────────────────────────────────────────

/**
 * Must be a DIFFERENT model from DRAFT_MODEL ("anthropic/claude-sonnet-4.5")
 * so the verifier is truly independent from the drafter.
 *
 * Exported so the cross-model invariant (`drafter !== verifier`) and the gate
 * config can be asserted in tests against `@sagemark/core`'s `config/models.ts`.
 */
export const GATE_MODEL = "anthropic/claude-haiku-4-5";
/**
 * Bug 2 fix: reduced from 30_000 to 12_000.
 * Haiku is fast — 12s is ample. Draft timeout is 45s; gate is 12s → worst-case
 * total is 57s, safely under maxDuration=60 in the route.
 *
 * Exported so the 12s-timeout budget can be asserted in tests (RFC §1 gate
 * latency floor; PR 002 acceptance criterion 2).
 */
export const GATE_TIMEOUT_MS = 12_000;
export const GATE_MAX_TOKENS = 2_000;
/**
 * Bug 3 cap: the verifier is instructed to focus on at most this many factual
 * claims so a long article cannot overflow GATE_MAX_TOKENS and truncate the
 * JSON (which would silently degrade to `skipped: true`). Named here so the cap
 * is assertable in tests (PR 002 acceptance criterion 2 — the 25-claim cap).
 */
export const GATE_CLAIM_CAP = 25;
const OPENROUTER_ENDPOINT = "https://openrouter.ai/api/v1/chat/completions";

/** UI threshold: show warning banner if sourcedPercent < this value. Re-exported from the client-safe constants module. */
export { FAITHFULNESS_WARNING_THRESHOLD } from "../scorers/faithfulness-gate-constants";

// ── Prompts ───────────────────────────────────────────────────────────────────

/**
 * Bug 3 fix: cap at 25 claims to avoid GATE_MAX_TOKENS truncation.
 * GATE_MAX_TOKENS=2000 can fit ~25 claims × ~30 tokens each = ~750 tokens for
 * claims, leaving headroom. Without the cap, a 1200-word article can exceed 40+
 * claims, risking JSON truncation → parse error → silent skipped:true.
 */
const GATE_SYSTEM = `You are a factual claim verifier. You will be given a draft article and the source documents it was supposed to be grounded in.

Your job:
1. Identify factual claims in the draft: statistics, specific numbers, attributed quotes, named entities with specific attributes (e.g. "Company X has 500 employees"), dated events, and comparisons. Focus on the ${GATE_CLAIM_CAP} most important factual claims (statistics, specific numbers, attributed quotes, named entities with specific attributes). Do not list all minor factual statements.
2. For each claim, determine:
   - SOURCED: the claim is explicitly supported by one of the provided sources (the source must contain the fact, not just be on the same topic)
   - UNSOURCED: the claim cannot be found in any provided source
   - CONTRADICTED: the claim directly conflicts with information in a provided source

Be strict about SOURCED — general topical overlap is not enough; the source must explicitly contain the stated fact, figure, or quote.

OUTPUT FORMAT:
Return valid JSON only — no prose, no markdown fences.
{
  "claims": [
    {
      "claim": "exact claim text from draft",
      "verdict": "SOURCED" | "UNSOURCED" | "CONTRADICTED",
      "sourceUrl": "url if SOURCED (omit otherwise)",
      "notes": "brief reason if CONTRADICTED (omit otherwise)"
    }
  ]
}

If the draft has no identifiable factual claims, return { "claims": [] }.`;

function buildGateUserMessage(
  draftBody: string,
  sources: Array<{ url: string; title: string; snippet: string }>,
): string {
  const sourceBlock = sources
    .map(
      (s, i) =>
        `[Source ${i + 1}] ${s.title}\nURL: ${s.url}\nContent: ${s.snippet}`,
    )
    .join("\n\n");

  return `DRAFT ARTICLE BODY:
${draftBody}

---

SOURCES (verify each claim against these only):
${sourceBlock}`;
}

// ── JSON schema for structured output ────────────────────────────────────────

const GATE_JSON_SCHEMA = {
  type: "object",
  properties: {
    claims: {
      type: "array",
      items: {
        type: "object",
        properties: {
          claim: { type: "string" },
          verdict: { type: "string", enum: ["SOURCED", "UNSOURCED", "CONTRADICTED"] },
          sourceUrl: { type: "string" },
          notes: { type: "string" },
        },
        required: ["claim", "verdict"],
        additionalProperties: false,
      },
    },
  },
  required: ["claims"],
  additionalProperties: false,
};

// ── Verdict computation ───────────────────────────────────────────────────────

function computeVerdict(
  claims: ClaimResult[],
): Pick<FaithfulnessResult, "sourcedPercent" | "sourcedCount" | "unsourcedCount" | "contradictedCount" | "verdict"> {
  const total = claims.length;

  if (total === 0) {
    // No identifiable factual claims — treat as fully faithful
    return {
      sourcedPercent: 100,
      sourcedCount: 0,
      unsourcedCount: 0,
      contradictedCount: 0,
      verdict: "FAITHFUL",
    };
  }

  const sourcedCount = claims.filter((c) => c.verdict === "SOURCED").length;
  const unsourcedCount = claims.filter((c) => c.verdict === "UNSOURCED").length;
  const contradictedCount = claims.filter((c) => c.verdict === "CONTRADICTED").length;
  const sourcedPercent = Math.round((sourcedCount / total) * 100);

  let verdict: "FAITHFUL" | "PARTIAL" | "UNFAITHFUL";
  if (contradictedCount > 0 || sourcedPercent < 50) {
    verdict = "UNFAITHFUL";
  } else if (sourcedPercent >= 80 && contradictedCount === 0) {
    verdict = "FAITHFUL";
  } else {
    verdict = "PARTIAL";
  }

  return { sourcedPercent, sourcedCount, unsourcedCount, contradictedCount, verdict };
}

// ── Skipped result factories ──────────────────────────────────────────────────

/** Bug 4 fix: two distinct skipped factories to distinguish the reason. */
function noSourcesResult(): FaithfulnessResult {
  return {
    skipped: true,
    skipReason: "no-sources",
    verdict: "PARTIAL",
    sourcedPercent: 0,
    totalClaims: 0,
    sourcedCount: 0,
    unsourcedCount: 0,
    contradictedCount: 0,
    claims: [],
  };
}

function gateErrorResult(): FaithfulnessResult {
  return {
    skipped: true,
    skipReason: "gate-error",
    verdict: "PARTIAL",
    sourcedPercent: 0,
    totalClaims: 0,
    sourcedCount: 0,
    unsourcedCount: 0,
    contradictedCount: 0,
    claims: [],
  };
}

// ── Main export ───────────────────────────────────────────────────────────────

/**
 * Run the cross-model faithfulness gate.
 *
 * @param draft   - the generated content draft (only `body` is used)
 * @param brief   - the content brief (only `sources` is used for verification)
 * @returns       FaithfulnessResult — never throws; failure returns skipped=true
 */
export async function runFaithfulnessGate(
  draft: { body: string },
  brief: { sources: Array<{ url: string; title: string; snippet: string }> },
): Promise<FaithfulnessResult> {
  // No sources available → skip gate (no basis for verification)
  if (brief.sources.length === 0) {
    return noSourcesResult();
  }

  const openrouterKey = process.env.OPENROUTER_API_KEY;
  if (!openrouterKey || openrouterKey.trim().length === 0) {
    return gateErrorResult();
  }

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), GATE_TIMEOUT_MS);

  let res: Response;
  try {
    res = await fetch(OPENROUTER_ENDPOINT, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${openrouterKey}`,
        "Content-Type": "application/json",
        "HTTP-Referer": "https://flywheel.love",
        "X-Title": "ContentEngine Faithfulness Gate",
      },
      body: JSON.stringify({
        model: GATE_MODEL,
        messages: [
          { role: "system", content: GATE_SYSTEM },
          {
            role: "user",
            content: buildGateUserMessage(draft.body, brief.sources),
          },
        ],
        max_tokens: GATE_MAX_TOKENS,
        temperature: 0.1, // low temperature for deterministic fact-checking
        response_format: {
          type: "json_schema",
          json_schema: {
            name: "faithfulness_gate",
            strict: true,
            schema: GATE_JSON_SCHEMA,
          },
        },
      }),
      signal: controller.signal,
    });
  } catch {
    clearTimeout(timer);
    // Network error, timeout, or abort → soft failure
    return gateErrorResult();
  }
  clearTimeout(timer);

  if (!res.ok) {
    return gateErrorResult();
  }

  let rawContent: string | undefined;
  try {
    const rawBody = (await res.json()) as {
      choices?: Array<{ message?: { content?: string } }>;
    };
    rawContent = rawBody.choices?.[0]?.message?.content;
  } catch {
    return gateErrorResult();
  }

  if (!rawContent || typeof rawContent !== "string") {
    return gateErrorResult();
  }

  // Parse the JSON response
  let parsed: unknown;
  try {
    const cleaned = rawContent.replace(/```(?:json)?/g, "").trim();
    const jsonStart = cleaned.indexOf("{");
    if (jsonStart === -1) return gateErrorResult();
    parsed = JSON.parse(cleaned.slice(jsonStart));
  } catch {
    return gateErrorResult();
  }

  // Validate shape
  if (
    typeof parsed !== "object" ||
    parsed === null ||
    !Array.isArray((parsed as Record<string, unknown>).claims)
  ) {
    return gateErrorResult();
  }

  const rawClaims = (parsed as { claims: unknown[] }).claims;

  // Coerce each claim into a ClaimResult, dropping malformed entries
  let claims: ClaimResult[] = rawClaims.flatMap((item) => {
    if (typeof item !== "object" || item === null) return [];
    const c = item as Record<string, unknown>;
    if (typeof c.claim !== "string" || typeof c.verdict !== "string") return [];
    const verdict = c.verdict as string;
    if (
      verdict !== "SOURCED" &&
      verdict !== "UNSOURCED" &&
      verdict !== "CONTRADICTED"
    ) {
      return [];
    }
    const result: ClaimResult = {
      claim: c.claim,
      verdict: verdict as ClaimVerdict,
    };
    if (verdict === "SOURCED" && typeof c.sourceUrl === "string") {
      result.sourceUrl = c.sourceUrl;
    }
    if (verdict === "CONTRADICTED" && typeof c.notes === "string") {
      result.notes = c.notes;
    }
    return [result];
  });

  // Minor fix: strip sourceUrl if it's not actually in brief.sources to prevent
  // hallucinated URLs from being rendered as clickable links in the UI.
  const validUrls = new Set(brief.sources.map((s) => s.url));
  claims = claims.map((c) => ({
    ...c,
    sourceUrl: c.sourceUrl && validUrls.has(c.sourceUrl) ? c.sourceUrl : undefined,
  }));

  const computed = computeVerdict(claims);

  return {
    skipped: false,
    totalClaims: claims.length,
    claims,
    ...computed,
  };
}
