/**
 * Cross-model faithfulness gate for ContentEngine (`content-engine/1.0`).
 *
 * After a draft is generated by the primary LLM (the drafter,
 * `DRAFTER_MODEL_ID` = claude-sonnet-4-6), this gate runs a DIFFERENT model
 * (the verifier, `VERIFIER_MODEL_ID` = claude-haiku-4-5) to independently
 * verify that every factual claim in the body traces to the provided source
 * snippets.
 *
 * Independence is the key invariant: the verifier model must differ from
 * the draft model so we get a genuine second opinion, not a self-consistency
 * check from the same weights. The verifier id is pulled from the canonical,
 * invariant-checked `config/models.ts` — never a literal — so it can never fork
 * from the drafter (`assertCrossModelInvariant` collapses the build if they
 * ever collapse to the same id).
 *
 * Transport (audit-001 fix, RFC §2): the gate routes its model call through the
 * metered Vercel **AI Gateway** seam (`resolveGatewayModel` + the AI SDK), NOT
 * a raw provider endpoint. Every model call is accounted (the D4 cost ledger is
 * built from live Gateway usage); the host/worker invariant is preserved (no
 * raw provider key is held here — the only model path is the Gateway seam).
 *
 * Gate failure (LLM error, parse error, timeout) is always soft:
 *   → returns { skipped: true, skipReason: 'gate-error', verdict: 'PARTIAL', ... }
 *   → the draft is never blocked
 *
 * PII rule: never log draft body or claim text.
 */

import "server-only";

import { generateText, Output } from "ai";
import { z } from "zod";

import { resolveGatewayModel } from "../ai/resolve-gateway-model";
import { VERIFIER_MODEL_ID } from "../config/models";

// ── Types ────────────────────────────────────────────────────────────────────

export type ClaimVerdict = "SOURCED" | "UNSOURCED" | "CONTRADICTED";

export interface ClaimResult {
  /** Exact claim text as it appears in the draft body */
  claim: string;
  verdict: ClaimVerdict;
  /** Which source URL supports it (populated for SOURCED claims; always a URL present in brief.sources) */
  sourceUrl?: string;
  /** Brief note explaining a contradiction (populated for CONTRADICTED claims) */
  notes?: string;
}

export interface FaithfulnessResult {
  /** 0-100 percentage of claims that are SOURCED */
  sourcedPercent: number;
  totalClaims: number;
  sourcedCount: number;
  unsourcedCount: number;
  contradictedCount: number;
  claims: ClaimResult[];
  /**
   * FAITHFUL:   ≥80% sourced AND 0 contradicted
   * PARTIAL:    50-79% sourced OR (<80% but 0 contradicted)
   * UNFAITHFUL: <50% sourced OR any CONTRADICTED
   */
  verdict: "FAITHFUL" | "PARTIAL" | "UNFAITHFUL";
  /**
   * true when no sources were available (sources[].length === 0)
   * or when the LLM call itself failed (gate failure = soft)
   */
  skipped: boolean;
  /**
   * Distinguishes WHY the gate was skipped:
   *   'no-sources'  — brief had no web sources to verify against
   *   'gate-error'  — LLM gate call failed (network, parse, timeout, etc.)
   * Only present when skipped === true.
   */
  skipReason?: "no-sources" | "gate-error";
}

// ── Constants ─────────────────────────────────────────────────────────────────

/**
 * The verifier model for the faithfulness gate. Pulled from the canonical,
 * invariant-checked `config/models.ts` (`VERIFIER_MODEL_ID` =
 * "anthropic/claude-haiku-4-5") rather than a hardcoded literal, so it can
 * never fork from — or collapse onto — the drafter ("anthropic/claude-sonnet-4-6").
 *
 * Exported so the cross-model invariant (`drafter !== verifier`) and the gate
 * config can be asserted in tests against `@sagemark/core`'s `config/models.ts`.
 */
export const GATE_MODEL = VERIFIER_MODEL_ID;
/**
 * Bug 2 fix: reduced from 30_000 to 12_000.
 * Haiku is fast — 12s is ample. Draft timeout is 45s; gate is 12s → worst-case
 * total is 57s, safely under maxDuration=60 in the route.
 *
 * Exported so the 12s-timeout budget can be asserted in tests (RFC §1 gate
 * latency floor; PR 002 acceptance criterion 2).
 */
export const GATE_TIMEOUT_MS = 12_000;
export const GATE_MAX_TOKENS = 2_000;
/**
 * Bug 3 cap: the verifier is instructed to focus on at most this many factual
 * claims so a long article cannot overflow GATE_MAX_TOKENS and truncate the
 * JSON (which would silently degrade to `skipped: true`). Named here so the cap
 * is assertable in tests (PR 002 acceptance criterion 2 — the 25-claim cap).
 */
export const GATE_CLAIM_CAP = 25;

/** UI threshold: show warning banner if sourcedPercent < this value. Re-exported from the client-safe constants module. */
export { FAITHFULNESS_WARNING_THRESHOLD } from "../scorers/faithfulness-gate-constants";

// ── Prompts ───────────────────────────────────────────────────────────────────

/**
 * Bug 3 fix: cap at 25 claims to avoid GATE_MAX_TOKENS truncation.
 * GATE_MAX_TOKENS=2000 can fit ~25 claims × ~30 tokens each = ~750 tokens for
 * claims, leaving headroom. Without the cap, a 1200-word article can exceed 40+
 * claims, risking JSON truncation → parse error → silent skipped:true.
 */
const GATE_SYSTEM = `You are a factual claim verifier. You will be given a draft article and the source documents it was supposed to be grounded in.

Your job:
1. Identify factual claims in the draft: statistics, specific numbers, attributed quotes, named entities with specific attributes (e.g. "Company X has 500 employees"), dated events, and comparisons. Focus on the ${GATE_CLAIM_CAP} most important factual claims (statistics, specific numbers, attributed quotes, named entities with specific attributes). Do not list all minor factual statements.
2. For each claim, determine:
   - SOURCED: the claim is explicitly supported by one of the provided sources (the source must contain the fact, not just be on the same topic)
   - UNSOURCED: the claim cannot be found in any provided source
   - CONTRADICTED: the claim directly conflicts with information in a provided source

Be strict about SOURCED — general topical overlap is not enough; the source must explicitly contain the stated fact, figure, or quote.

OUTPUT FORMAT:
Return valid JSON only — no prose, no markdown fences.
{
  "claims": [
    {
      "claim": "exact claim text from draft",
      "verdict": "SOURCED" | "UNSOURCED" | "CONTRADICTED",
      "sourceUrl": "url if SOURCED (omit otherwise)",
      "notes": "brief reason if CONTRADICTED (omit otherwise)"
    }
  ]
}

If the draft has no identifiable factual claims, return { "claims": [] }.`;

function buildGateUserMessage(
  draftBody: string,
  sources: Array<{ url: string; title: string; snippet: string }>,
): string {
  const sourceBlock = sources
    .map(
      (s, i) =>
        `[Source ${i + 1}] ${s.title}\nURL: ${s.url}\nContent: ${s.snippet}`,
    )
    .join("\n\n");

  return `DRAFT ARTICLE BODY:
${draftBody}

---

SOURCES (verify each claim against these only):
${sourceBlock}`;
}

// ── Zod schema for structured output (AI SDK `Output.object`) ─────────────────
//
// Mirrors the prior OpenRouter `json_schema`: a `claims[]` array where each entry
// carries `claim` + `verdict` (required) and optional `sourceUrl` / `notes`. The
// AI SDK validates the model output against this; a violation throws and is
// caught as a fail-closed gate-error below.

const GATE_OUTPUT_SCHEMA = z.object({
  claims: z.array(
    z.object({
      claim: z.string(),
      verdict: z.enum(["SOURCED", "UNSOURCED", "CONTRADICTED"]),
      sourceUrl: z.string().optional(),
      notes: z.string().optional(),
    }),
  ),
});

// ── Verdict computation ───────────────────────────────────────────────────────

function computeVerdict(
  claims: ClaimResult[],
): Pick<FaithfulnessResult, "sourcedPercent" | "sourcedCount" | "unsourcedCount" | "contradictedCount" | "verdict"> {
  const total = claims.length;

  if (total === 0) {
    // No identifiable factual claims — treat as fully faithful
    return {
      sourcedPercent: 100,
      sourcedCount: 0,
      unsourcedCount: 0,
      contradictedCount: 0,
      verdict: "FAITHFUL",
    };
  }

  const sourcedCount = claims.filter((c) => c.verdict === "SOURCED").length;
  const unsourcedCount = claims.filter((c) => c.verdict === "UNSOURCED").length;
  const contradictedCount = claims.filter((c) => c.verdict === "CONTRADICTED").length;
  const sourcedPercent = Math.round((sourcedCount / total) * 100);

  let verdict: "FAITHFUL" | "PARTIAL" | "UNFAITHFUL";
  if (contradictedCount > 0 || sourcedPercent < 50) {
    verdict = "UNFAITHFUL";
  } else if (sourcedPercent >= 80 && contradictedCount === 0) {
    verdict = "FAITHFUL";
  } else {
    verdict = "PARTIAL";
  }

  return { sourcedPercent, sourcedCount, unsourcedCount, contradictedCount, verdict };
}

// ── Skipped result factories ──────────────────────────────────────────────────

/** Bug 4 fix: two distinct skipped factories to distinguish the reason. */
function noSourcesResult(): FaithfulnessResult {
  return {
    skipped: true,
    skipReason: "no-sources",
    verdict: "PARTIAL",
    sourcedPercent: 0,
    totalClaims: 0,
    sourcedCount: 0,
    unsourcedCount: 0,
    contradictedCount: 0,
    claims: [],
  };
}

function gateErrorResult(): FaithfulnessResult {
  return {
    skipped: true,
    skipReason: "gate-error",
    verdict: "PARTIAL",
    sourcedPercent: 0,
    totalClaims: 0,
    sourcedCount: 0,
    unsourcedCount: 0,
    contradictedCount: 0,
    claims: [],
  };
}

// ── Main export ───────────────────────────────────────────────────────────────

/**
 * Run the cross-model faithfulness gate.
 *
 * @param draft   - the generated content draft (only `body` is used)
 * @param brief   - the content brief (only `sources` is used for verification)
 * @returns       FaithfulnessResult — never throws; failure returns skipped=true
 */
export async function runFaithfulnessGate(
  draft: { body: string },
  brief: { sources: Array<{ url: string; title: string; snippet: string }> },
): Promise<FaithfulnessResult> {
  // No sources available → skip gate (no basis for verification)
  if (brief.sources.length === 0) {
    return noSourcesResult();
  }

  // Bug 2 timeout preserved: the gate self-aborts after GATE_TIMEOUT_MS. The
  // AbortController feeds the AI SDK call's `abortSignal`, so a slow Gateway
  // round-trip degrades soft (gate-error) instead of blocking the draft.
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), GATE_TIMEOUT_MS);

  // Route the verifier call through the metered AI Gateway seam (audit-001):
  // resolveGatewayModel + the AI SDK. No raw provider endpoint, no
  // OPENROUTER_API_KEY — the Gateway seam is the only model path, so this call
  // is accounted in the D4 cost ledger. Host context: gate verification runs in
  // the host/operator runtime (the BYOK escape hatch is host-only; production
  // host traffic still meters through the Gateway).
  let rawClaims: unknown[];
  try {
    const model = await resolveGatewayModel(GATE_MODEL, "host");
    const { output } = await generateText({
      model,
      system: GATE_SYSTEM,
      prompt: buildGateUserMessage(draft.body, brief.sources),
      maxOutputTokens: GATE_MAX_TOKENS,
      temperature: 0.1, // low temperature for deterministic fact-checking
      abortSignal: controller.signal,
      output: Output.object({ schema: GATE_OUTPUT_SCHEMA }),
    });
    rawClaims = output.claims;
  } catch {
    // Network error, timeout/abort, provider error, or output-validation
    // failure → soft failure (the draft is never blocked).
    return gateErrorResult();
  } finally {
    clearTimeout(timer);
  }

  // Coerce each claim into a ClaimResult, dropping malformed entries
  let claims: ClaimResult[] = rawClaims.flatMap((item) => {
    if (typeof item !== "object" || item === null) return [];
    const c = item as Record<string, unknown>;
    if (typeof c.claim !== "string" || typeof c.verdict !== "string") return [];
    const verdict = c.verdict as string;
    if (
      verdict !== "SOURCED" &&
      verdict !== "UNSOURCED" &&
      verdict !== "CONTRADICTED"
    ) {
      return [];
    }
    const result: ClaimResult = {
      claim: c.claim,
      verdict: verdict as ClaimVerdict,
    };
    if (verdict === "SOURCED" && typeof c.sourceUrl === "string") {
      result.sourceUrl = c.sourceUrl;
    }
    if (verdict === "CONTRADICTED" && typeof c.notes === "string") {
      result.notes = c.notes;
    }
    return [result];
  });

  // Minor fix: strip sourceUrl if it's not actually in brief.sources to prevent
  // hallucinated URLs from being rendered as clickable links in the UI.
  const validUrls = new Set(brief.sources.map((s) => s.url));
  claims = claims.map((c) => ({
    ...c,
    sourceUrl: c.sourceUrl && validUrls.has(c.sourceUrl) ? c.sourceUrl : undefined,
  }));

  const computed = computeVerdict(claims);

  return {
    skipped: false,
    totalClaims: claims.length,
    claims,
    ...computed,
  };
}
