/**
 * ImageGen — Persist + URL resolution (`imagegen/1`).
 *
 * PORTED from flywheel-main `packages/videogen/imagegen/persist.ts` and ADAPTED
 * for the SEO Creator: the bucket is `seo-generated-images` (SEO context) and
 * the asset/license types are the INLINED self-contained ones from `./assets`
 * (no videogen dependency). The provenance record gains SEO tenancy fields
 * (`clientId`) alongside `workspaceId`. The reference's `projectId`/`chapterId`
 * map to the SEO `clientId`/`slug`.
 *
 * Turns generated bytes into a durable, renderable asset + a provenance record:
 *   bytes → content-hash → upload to the generated bucket
 *         → asset row (source:"generated", generated license)
 *         → generation provenance row.
 *
 * Storage + DB are an INJECTED `GeneratedImageStore` so this is unit-testable
 * with a fake (no live Supabase). The live (Stage-2) store is wired separately.
 */

import { createHash } from "node:crypto";
import {
  assertLicensePresentForSource,
  makeGeneratedLicense,
  type Asset,
  type GeneratedAssetLicense,
} from "./assets";
import type { CanonicalImageSpec } from "./spec";
import type { GeneratedImage } from "./generate";

/** Bucket + prefix for generated SEO images (Stage-2 provisions the bucket+RLS). */
export const GENERATED_IMAGE_BUCKET = "seo-generated-images" as const;
export const GENERATED_IMAGE_PREFIX = "generated" as const;

/** sha256 hex of the image bytes (dedup key). */
export function contentHashOf(bytes: Uint8Array): string {
  return createHash("sha256").update(bytes).digest("hex");
}

/** Map a content type to a file extension for the storage key. */
function extFor(contentType: string): string {
  if (/png/i.test(contentType)) return "png";
  if (/jpe?g/i.test(contentType)) return "jpg";
  if (/webp/i.test(contentType)) return "webp";
  return "png";
}

/** The storage key for a generated image: `${ws}/generated/<hash>.<ext>`. */
export function generatedStorageKey(opts: {
  workspaceId: string;
  contentHash: string;
  contentType: string;
}): string {
  return `${opts.workspaceId}/${GENERATED_IMAGE_PREFIX}/${opts.contentHash}.${extFor(
    opts.contentType,
  )}`;
}

/** Lineage flags captured at write time (Bible ch.11: "lineage or never"). */
export interface ProvenanceFlags {
  /** Google SynthID watermark present in the output. */
  synthidPresent: boolean;
  /** Upstream C2PA manifest present. */
  c2paPresent: boolean;
  /** The provider's rewritten prompt, if it returned one. */
  revisedPrompt?: string;
  /** Raw provider metadata, untouched, for archaeology. */
  providerRaw?: unknown;
}

/**
 * Derive provenance flags from the provider metadata. Best-effort: looks for
 * SynthID / C2PA markers and a revised-prompt field across the nested provider
 * shapes. Always returns a record (never throws) so persist can't fail on it.
 */
export function deriveProvenanceFlags(
  providerMetadata: unknown,
): ProvenanceFlags {
  const flags: ProvenanceFlags = {
    synthidPresent: false,
    c2paPresent: false,
    providerRaw: providerMetadata,
  };
  if (!providerMetadata || typeof providerMetadata !== "object") return flags;
  const blob = JSON.stringify(providerMetadata).toLowerCase();
  flags.synthidPresent = blob.includes("synthid");
  flags.c2paPresent =
    blob.includes("c2pa") || blob.includes("contentcredentials");
  for (const value of Object.values(
    providerMetadata as Record<string, unknown>,
  )) {
    if (value && typeof value === "object") {
      const rp =
        (value as Record<string, unknown>).revisedPrompt ??
        (value as Record<string, unknown>).revised_prompt;
      if (typeof rp === "string") flags.revisedPrompt = rp;
    }
  }
  return flags;
}

/** The provenance row written to the generation log (SEO tenancy fields). */
export interface GenerationRecord {
  workspaceId: string;
  /** SEO tenancy: the client/site this image belongs to. */
  clientId: string;
  /** The page slug / brief id this image was generated for. */
  slug: string;
  spec: CanonicalImageSpec;
  provider: string;
  modelId: string;
  modelVersion: string;
  promptHash: string;
  seed?: number;
  costCredits: number;
  costReported?: number;
  /** AI-generated license marker (SEO Never-list #8: no unlicensed assets). */
  license: GeneratedAssetLicense;
  status: "succeeded" | "rejected" | "failed";
  assetId?: string;
  /** sha256 of the persisted bytes — captured here, impossible to back-fill. */
  contentHash: string;
  /** Lineage flags (SynthID/C2PA/revised-prompt) captured at write time. */
  provenance: ProvenanceFlags;
  /** ISO timestamp the image was generated at (provenance). */
  generatedAt: string;
}

/**
 * Injected storage + DB boundary. Workspace-scoped (Stage-2 enforces RLS on the
 * real Supabase impl). The in-memory fake + the fail-closed NOT_WIRED store both
 * satisfy this interface.
 */
export interface GeneratedImageStore {
  upload(args: {
    bucket: string;
    key: string;
    bytes: Uint8Array;
    contentType: string;
  }): Promise<void>;
  /** Find an existing generated asset by (workspace, contentHash); dedup. */
  findAssetByHash(args: {
    workspaceId: string;
    contentHash: string;
  }): Promise<Asset | null>;
  insertAsset(row: {
    workspaceId: string;
    source: "generated";
    storageKey: string;
    contentHash: string;
    bytes: number;
    license: GeneratedAssetLicense;
    tags: string[];
  }): Promise<Asset>;
  insertGenerationRecord(record: GenerationRecord): Promise<void>;
}

export interface PersistGeneratedImageArgs {
  store: GeneratedImageStore;
  workspaceId: string;
  clientId: string;
  slug: string;
  spec: CanonicalImageSpec;
  promptHash: string;
  generated: GeneratedImage;
  costCredits: number;
  /** Override the model-license-terms note on the generated license. */
  licenseTerms?: string;
  /** ISO timestamp for the provenance row (defaults to now). */
  generatedAt?: string;
}

/** What persist returns: the kept asset + the license recorded on it. */
export interface PersistResult {
  asset: Asset;
  license: GeneratedAssetLicense;
  contentHash: string;
}

/**
 * Persist a generated image. Dedups by content hash (re-uploading identical
 * bytes within a workspace returns the existing asset). Always writes a
 * provenance record carrying the AI-generated license. Returns the kept asset +
 * the license + the content hash.
 */
export async function persistGeneratedImage(
  args: PersistGeneratedImageArgs,
): Promise<PersistResult> {
  const { store, generated } = args;
  const contentHash = contentHashOf(generated.bytes);

  const license = makeGeneratedLicense({
    model: `${generated.modelId}@${generated.modelVersion}`,
    terms: args.licenseTerms,
  });
  // Fail fast if the generated license shape is ever wrong (Never-list #8 guard).
  assertLicensePresentForSource({ source: "generated", license });

  const existing = await store.findAssetByHash({
    workspaceId: args.workspaceId,
    contentHash,
  });

  let asset: Asset;
  if (existing) {
    asset = existing;
  } else {
    const key = generatedStorageKey({
      workspaceId: args.workspaceId,
      contentHash,
      contentType: generated.contentType,
    });
    await store.upload({
      bucket: GENERATED_IMAGE_BUCKET,
      key,
      bytes: generated.bytes,
      contentType: generated.contentType,
    });
    asset = await store.insertAsset({
      workspaceId: args.workspaceId,
      source: "generated",
      storageKey: key,
      contentHash,
      bytes: generated.bytes.length,
      license,
      tags: ["generated", `model:${generated.modelId}`],
    });
  }

  await store.insertGenerationRecord({
    workspaceId: args.workspaceId,
    clientId: args.clientId,
    slug: args.slug,
    spec: args.spec,
    provider: generated.modelId.split("/")[0] ?? "unknown",
    modelId: generated.modelId,
    modelVersion: generated.modelVersion,
    promptHash: args.promptHash,
    seed: generated.seedUsed,
    costCredits: args.costCredits,
    costReported: generated.costReported,
    license,
    status: "succeeded",
    assetId: asset.id,
    contentHash,
    provenance: deriveProvenanceFlags(generated.providerMetadata),
    generatedAt: args.generatedAt ?? new Date().toISOString(),
  });

  return { asset, license, contentHash };
}

// ── Render URL resolution ───────────────────────────────────────────

/** The minimal asset shape the renderer serializes + mounts. */
export interface RenderableAsset {
  externalUrl: string | null;
  storageKey: string | null;
  [k: string]: unknown;
}

/**
 * Resolve a renderable asset's URL at SERIALIZE time. If the asset already has
 * an `externalUrl`, it is returned unchanged. If it only has a `storageKey`,
 * mint a FRESH signed URL now so the render — and any LATER re-render — never
 * sees an expired link. `signUrl` is injected.
 */
export async function resolveGeneratedAssetUrl<T extends RenderableAsset>(
  asset: T,
  deps: {
    workspaceId: string;
    signUrl: (args: { key: string; workspaceId: string }) => Promise<string>;
  },
): Promise<T> {
  if (asset.externalUrl) return asset;
  if (!asset.storageKey) return asset;
  const signedUrl = await deps.signUrl({
    key: asset.storageKey,
    workspaceId: deps.workspaceId,
  });
  return { ...asset, externalUrl: signedUrl };
}
